# Town home icon
home-icon: MANSION

# Town colors
town:
  neutral: 255, 255, 0
  member_town: 0, 255, 0
  allied_town: 0, 0, 255
  member_nation: 0, 128, 0
  allied_nation: 0, 0, 128
  enemy_nation: 255, 0, 0
border-range: 1000
border-max-zoom: 16

# Player icons
# The global range is how close they must be to show up on your map
# The town range is how close they must be if they are in one of your towns that you own
show-name: true
player:
  neutral:
    enabled: true
    icon: PLAYER WHITE_POINTER
    global-range: 50
    town-range: 1000
    max-zoom: 16
  member_town: 
    enabled: true
    icon: FRAME GREEN_POINTER
    global-range: 150
    town-range: 1000
    max-zoom: 16
  allied_town:
    enabled: true
    icon: FRAME GREEN_POINTER
    global-range: 100
    town-range: 1000
    max-zoom: 16
  member_nation:
    enabled: true
    icon: BLUE_MARKER BLUE_POINTER
    global-range: 150
    town-range: 1000
    max-zoom: 16
  allied_nation:
    enabled: true
    icon: BLUE_MARKER BLUE_POINTER
    global-range: 100
    town-range: 1000
    max-zoom: 16
  enemy_nation:
    enabled: true
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    global-range: 50
    town-range: 1000
    max-zoom: 16